// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcJxo2ed0eJJtMM9ojFlCoSX9O5iPrjJY',
    appId: '1:138700460734:android:c2223161584882315244ef',
    messagingSenderId: '138700460734',
    projectId: 'mood-cast-23dff',
    storageBucket: 'mood-cast-23dff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB13F60CTriJ9l3Fv-tQLi8SP658zJ1gQw',
    appId: '1:138700460734:ios:d5d100840ee43d305244ef',
    messagingSenderId: '138700460734',
    projectId: 'mood-cast-23dff',
    storageBucket: 'mood-cast-23dff.firebasestorage.app',
    androidClientId: '138700460734-d1seea5ph5dt6758j69nlnlpc7ler8of.apps.googleusercontent.com',
    iosClientId: '138700460734-r5i2i1pv61me0atkucsj598qcori9gda.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodcast',
  );
}
